### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by ProjectsHiProjects** [ProjectsHiProjects/Hacktoberfest-22#1]
You have to create an attractive and visually appealing animation using HTML, CSS(or its framework), JavaScript.

**Comment by Atulsoam562003** [comment]
Hello. I can work on this. You can assign it to me if no one has already requested it. Thankyou.

**Comment by heza-ru** [comment]
Hello, I attempted this issue please review.

**Comment by lakshyaagr1105** [comment]
Hi @ProjectsHiProjects , I am Lakshya and i would be very happy to work on this issue and i have past experience with css animations so kindly assign me this issue

**Comment by RAHUL14KUMAR** [comment]
hi i am hacktoberfest participant.
can you please assign this issue to me as i have past experience in playing with css animation

**Comment by himanshu17-2000** [comment]
I wanna work on this  issue
