### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by ProjectsHiProjects** [ProjectsHiProjects/Hacktoberfest-22#10]

**Comment by Anshumansengar** [comment]
Hey, I would like to work on it. Pls Assign me.

**Comment by Anshumansengar** [comment]
https://github.com/ProjectsHiProjects/Hacktoberfest-22/pull/12

**Comment by aryanayush012** [comment]
I want to contribute. pleaase assign this to me. @Anshumansengar
